version: '1.0'
steps:
  build_step_name:
    type: build
    image-name: nikolai/test
    dockerfile: Dockerfile
    working_directory: ${{main_clone}}
    tag: ${{CF_SHORT_REVISION}}

  simple_travis_step:
    type: simple_travis
    services:
      - redis
      - memcached
      - mariadb
    test_1:
      image: redis:latest
      command: sh -c 'sleep 30 | redis-cli -h redis'
    test_2:
      image: redis:latest
      command: sh -c 'sleep 30 | redis-cli -h redis'

  simple_travis_step_lots_of_stuff:
    type: simple_travis
    services: [ redis, postgresql, mongodb, mysql, couchdb, rabbitmq, memcached ]
    test:
      image: redis:latest
      command: sh -c 'sleep 30 | redis-cli -h redis'