version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todo
    command: sh ${{CF_VOLUME_PATH}}/scripts/psql.sh
